<a href="https://colab.research.google.com/github/narasimha-nani/Hill-and-valley-prediction/blob/main/PROJECT_01_HILL__AND__VALLEY_PREDECTION_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TITLE OF THE PROJECT:

#Hill and Valley prediction

#Import library

In [ ]:
#STEP:1-Import the library
import pandas as pd

In [ ]:

import numpy as np


#Import data

In [ ]:
 #STEP:2-Import data
df=pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Hill%20Valley%20Dataset.csv')

#Data visualization

In [ ]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0     39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1      1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2  68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3  44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4      5.70      5.40      5.28      5.38      5.27      5.61      6.00   

         V8        V9       V10  ...       V92       V93       V94       V95  \
0     39.53     38.81     38.79  ...     36.62     36.92     38.80     38.52   
1      1.70      1.75      1.78  ...      1.80      1.79      1.77      1.74   
2  73268.61  74465.84  72503.37  ...  73438.88  71053.35  71112.62  74916.48   
3  37668.32  40980.89  38466.15  ...  42625.67  40684.20  46960.73  44546.80   
4      5.38      5.34      5.87  ...      5.17      5.67      5.60      5.94   

        V96       V97       V98       V99      V100  Class  
0     38.07     36.73     39.46     37.50     39.10      0  
1      1.74      1.80      1.78      1.75      1.69      1  
2  72571.58  66348.97  71063.72  67404.27  74920.24      1  
3  45410.53  47139.44  43095.68  40888.34  39615.19      0  
4      5.73      5.22      5.30      5.73      5.91      0  

[5 rows x 101 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Columns: 101 entries, V1 to Class
dtypes: float64(100), int64(1)
memory usage: 956.5 KB


In [ ]:
df.describe()

V1             V2             V3             V4  \
count    1212.000000    1212.000000    1212.000000    1212.000000   
mean     8169.091881    8144.306262    8192.653738    8176.868738   
std     17974.950461   17881.049734   18087.938901   17991.903982   
min         0.920000       0.900000       0.850000       0.890000   
25%        19.602500      19.595000      18.925000      19.277500   
50%       301.425000     295.205000     297.260000     299.720000   
75%      5358.795000    5417.847500    5393.367500    5388.482500   
max    117807.870000  108896.480000  119031.350000  110212.590000   

                  V5             V6             V7             V8  \
count    1212.000000    1212.000000    1212.000000    1212.000000   
mean     8128.297211    8173.030008    8188.582748    8183.641543   
std     17846.757963   17927.114105   18029.562695   18048.582159   
min         0.880000       0.860000       0.870000       0.650000   
25%        19.210000      19.582500      18.690000      19.062500   
50%       295.115000     294.380000     295.935000     290.850000   
75%      5321.987500    5328.040000    5443.977500    5283.655000   
max    113000.470000  116848.390000  115609.240000  118522.320000   

                  V9            V10  ...            V92            V93  \
count    1212.000000    1212.000000  ...    1212.000000    1212.000000   
mean     8154.670066    8120.767574  ...    8120.056815    8125.917409   
std     17982.390713   17900.798206  ...   17773.190621   17758.182403   
min         0.650000       0.620000  ...       0.870000       0.900000   
25%        19.532500      19.285000  ...      19.197500      18.895000   
50%       294.565000     295.160000  ...     297.845000     295.420000   
75%      5378.180000    5319.097500  ...    5355.355000    5386.037500   
max    112895.900000  117798.300000  ...  113858.680000  112948.830000   

                 V94            V95            V96            V97  \
count    1212.000000    1212.000000    1212.000000    1212.000000   
mean     8158.793812    8140.885421    8213.480611    8185.594002   
std     17919.510371   17817.945646   18016.445265   17956.084223   
min         0.870000       0.880000       0.890000       0.890000   
25%        19.237500      19.385000      19.027500      19.135000   
50%       299.155000     293.355000     301.370000     296.960000   
75%      5286.385000    5345.797500    5300.890000    5361.047500   
max    112409.570000  112933.730000  112037.220000  115110.420000   

                 V98            V99           V100        Class  
count    1212.000000    1212.000000    1212.000000  1212.000000  
mean     8140.195355    8192.960891    8156.197376     0.500000  
std     17768.356106   18064.781479   17829.310973     0.500206  
min         0.860000       0.910000       0.890000     0.000000  
25%        19.205000      18.812500      19.145000     0.000000  
50%       300.925000     299.200000     302.275000     0.500000  
75%      5390.850000    5288.712500    5357.847500     1.000000  
max    116431.960000  113291.960000  114533.760000     1.000000  

[8 rows x 101 columns]

In [ ]:
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       ...
       'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100',
       'Class'],
      dtype='object', length=101)

#Define Target Variable (y) and Feature Variables (X)


In [ ]:
#STEP:3-Define target[y] and features[[x]]
y=df['Class']
X = df.drop(['Class'], axis=1)

In [ ]:
y.shape

(1212,)

In [ ]:
X.shape

(1212, 100)

#Train Test Split

In [ ]:
 # Step 4 : train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,stratify=y,random_state=2529)


#Modeling

In [ ]:
# Step 5 : select model
from sklearn.linear_model import LogisticRegression

In [ ]:
model= LogisticRegression()

#Train and Fit the Model

In [ ]:
# Step 6 : train or fit model
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
model.intercept_

array([-0.00020785])

In [ ]:
model.coef_

array([[-0.10804399, -0.08096682, -0.09695977, -0.08700256, -0.07603003,
        -0.05973469, -0.01057651, -0.01655597, -0.01350578,  0.04209078,
         0.03990607,  0.03006226,  0.01650336,  0.01463398,  0.09260181,
         0.01962994,  0.00193994,  0.02359829,  0.02182972,  0.00588502,
        -0.00051337, -0.01856228,  0.01783268, -0.00058771,  0.03306996,
         0.02923714,  0.02960278,  0.00627646,  0.00865103, -0.01258142,
         0.01672119,  0.01032044,  0.00045768, -0.02239699,  0.00295855,
         0.02803265,  0.03434992, -0.00494731,  0.00895396,  0.01247824,
         0.02539181,  0.01619269,  0.00961933, -0.00200295,  0.00705909,
         0.02121765, -0.00562942, -0.00494219, -0.01404882,  0.05128014,
         0.0214318 , -0.00072858,  0.03086711,  0.04628618,  0.01819873,
         0.01144394, -0.00290219, -0.00026694, -0.01961505,  0.01988302,
         0.00579581,  0.02700837,  0.02080636,  0.01349936,  0.0099611 ,
         0.01538869,  0.00563546, -0.00770575,  0.0

#Predict the Model

In [ ]:
# Step 7 : predict model
y_pred=model.predict(X_test)

In [ ]:
y_pred

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,

#Accuracy of the Model

In [ ]:
# Step 8 : model accuracy
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error


In [ ]:
mean_absolute_error(y_test,y_pred)

0.03021978021978022

In [ ]:
mean_absolute_percentage_error(y_test,y_pred)

86607685141740.31

In [ ]:
mean_squared_error(y_test,y_pred)

0.03021978021978022